// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $.fn.cmd_t = function(options) {
      var $elements, $filter_function, $search_field;
      $search_field = this;
      $elements = options.elements;
      $filter_function = options.filter;
      $search_field.on("keyup", function() {
        var query, re;
        query = $(this).val().toLowerCase();
        re = new RegExp(query, "i");
        return $elements.each(function(i, elem) {
          var name;
          name = $filter_function.call(elem);
          if (name.match(re) != null) {
            return $(elem).show();
          } else {
            return $(elem).hide();
          }
        });
      });
      return $(document).keyup(function(e) {
        var keyCode;
        e = e || window.event;
        keyCode = e.keyCode || e.which;
        if (keyCode === 84) {
          $search_field.focus();
          e.preventDefault();
        }
        if (keyCode === 27 && $(":focus").prop("id") === "project_filter") {
          $search_field.val("");
          $search_field.trigger("keyup");
          $search_field.blur();
          return e.preventDefault();
        }
      });
    };
  });

}).call(this);
