// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $.fn.cmd_t = function(options) {
      var $elements, $filter_function, $search_field;
      $search_field = this;
      $elements = options.elements;
      $filter_function = options.filter;
      return $search_field.on("keyup", function() {
        var query, re;
        query = $(this).val().toLowerCase();
        re = new RegExp(query, "i");
        return $elements.each(function(i, elem) {
          var name;
          name = $filter_function.call(elem);
          if (name.match(re) != null) {
            return $(elem).show();
          } else {
            return $(elem).hide();
          }
        });
      });
    };
  });

}).call(this);

